development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: winnamoney_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: winnamoney_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: winna_production
  pool: 5
  username: winna
  password: soyinnku09
  socket: /tmp/mysql.sock
  
staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: winna_staging
  pool: 5
  username: winna_winna
  password: soyinnku09
  socket: /tmp/mysql.sock